### ISSUE TITLE
Prevent doctors to register several times

### ISSUE THREAD

**Issue by jadsanders** [sofort-impfen-de/services#18]
<img width="1358" alt="Screenshot 2021-06-08 at 19 01 41" src="https://user-images.githubusercontent.com/16987647/121227602-07fe1200-c88c-11eb-8d0d-501e0a6210da.png">

<img width="1384" alt="Screenshot 2021-06-08 at 19 01 51" src="https://user-images.githubusercontent.com/16987647/121227614-0b919900-c88c-11eb-8579-ee95f2b2d43d.png">

**Comment by adewes** [comment]
This should already be implemented, provider can't reuse the same code to sign up more than once.

**Comment by adewes** [comment]
(I think there are still some duplicates from before that was possible)
